# Generated by Django 5.2.8 on 2025-12-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreturn',
            name='mc_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreturn',
            name='mc_given_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productreturn',
            name='mc_amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
