# Generated by Django 5.2.5 on 2025-11-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mc_type', models.CharField(choices=[('per_gram', 'MC per Gram'), ('per_kg', 'MC per KG')], default='per_kg', max_length=20)),
                ('mc_rate', models.FloatField()),
            ],
        ),
    ]
